apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
    pod-template-hash: 77776fdcdc
  name: nginx-77776fdcdc-aabbcc
  namespace: default
spec:
  containers:
   - image: nginx:1.16
     name: nginx
