apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql 
  name: mysql-service
  namespace: default
spec:
  ports:
  - nodePort: 31000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mysql
    tier: backend
  type: NodePort
